#import os
#import glob
#modules = glob.glob(os.path.dirname(__file__)+"/*.py")
#__all__ = [ os.path.basename(f)[:-3] for f in modules]
__customer_businesses_businessgrps_tablename__ = 'customer_businesses_businessgrps'
__customer_businesses_tablename__ = 'customer_businesses'
__customer_business_details_tablename__ = 'customer_business_details'
__customer_business_comments_tablename__ = 'customer_business_comments'
__customer_business_details_comments_tablename__ = 'customer_business_details_comments'
__customer_business_pics_tablename__ = 'customer_business_pics'
__customer_business_deals_tablename__ = 'customer_business_deals'
__customer_business_rates_tablename__ = 'customer_business_rates'
__customer_business_favorite_tablename__ = 'customer_business_favorite'
__customer_businessgrps_tablename__ = 'customer_businessgrps'
__customer_businessgrp_heads__ = 'businessgrps'
__customer_businessgrp_head__ = 'businessgrp'
__customer_business_heads__ = 'businesses'
__customer_business_head__ = 'business'
__customer_business_detail_head__ = 'detail'
__customer_business_detail_rates_head__ = 'rates'
__customer_business_detail_deals_head__ = 'deals'
__customer_business_detail_images_url_head__ = 'images_url'
__customer_comment_heads__ = 'comments'
__customer_comment_head__ = 'comment'
__customer_comment_user_head__ = 'user'
__customer_rate_heads__ = 'rates'
__customer_rate_head__ = 'rate'
